/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.apiconnection;

import javax.swing.JOptionPane;

/**
 *
 * @author rokom
 */
public class VerificationGUI extends javax.swing.JFrame {

    private GUIManager guiManager;
    private MongoDBManager mongoManager;
    private MongoDBManager portfolioManager;
    private int[] verificationCode;
    private String username, password, emailAddress;
    /**
     * Creates new form VerificationGUI
     */
    public VerificationGUI() {
        initComponents();
    }
    
    public void setGUIManager(GUIManager gui) {
        guiManager = gui;
    }
    
    public void setVerificationCode(int[] array) {
        verificationCode = array;
    }
    
    public void setMongoManager(MongoDBManager mongo) {
        mongoManager = mongo;
    }
    
    public void setCredentials(String user, String pw, String email) {
        username = user;
        password = pw;
        emailAddress = email;
    }
    
    public void modifyMessage() {
        help2LBL.setText("as shown in the confirmation email sent to " + emailAddress);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titleLBL = new javax.swing.JLabel();
        help1LBL = new javax.swing.JLabel();
        help2LBL = new javax.swing.JLabel();
        firstDigitTF = new javax.swing.JTextField();
        fourthDigitTF = new javax.swing.JTextField();
        secondDigitTF = new javax.swing.JTextField();
        thirdDigitTF = new javax.swing.JTextField();
        confirmBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cryptochaun");
        setName("verificationFrame"); // NOI18N

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));

        titleLBL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        titleLBL.setForeground(new java.awt.Color(255, 255, 255));
        titleLBL.setText("Verification");

        help1LBL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        help1LBL.setForeground(new java.awt.Color(255, 255, 255));
        help1LBL.setText("To complete your registration, please enter the 4-digit verification code");

        help2LBL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        help2LBL.setForeground(new java.awt.Color(255, 255, 255));
        help2LBL.setText("as shown in the confirmation email. ");

        firstDigitTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        firstDigitTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstDigitTFActionPerformed(evt);
            }
        });

        fourthDigitTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fourthDigitTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourthDigitTFActionPerformed(evt);
            }
        });

        secondDigitTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        secondDigitTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondDigitTFActionPerformed(evt);
            }
        });

        thirdDigitTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        thirdDigitTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thirdDigitTFActionPerformed(evt);
            }
        });

        confirmBTN.setText("Confirm");
        confirmBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(help2LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(help1LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(titleLBL))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(firstDigitTF, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(secondDigitTF, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(thirdDigitTF, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(confirmBTN))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fourthDigitTF, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(206, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(titleLBL)
                .addGap(18, 18, 18)
                .addComponent(help1LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(help2LBL)
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstDigitTF, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fourthDigitTF, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(secondDigitTF, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(thirdDigitTF, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(confirmBTN)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void firstDigitTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstDigitTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstDigitTFActionPerformed

    private void fourthDigitTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourthDigitTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fourthDigitTFActionPerformed

    private void secondDigitTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondDigitTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_secondDigitTFActionPerformed

    private void thirdDigitTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thirdDigitTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_thirdDigitTFActionPerformed

    private void confirmBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBTNActionPerformed
        // TODO add your handling code here:
        if (firstDigitTF.getText().equals(String.valueOf(verificationCode[0])) &&
                secondDigitTF.getText().equals(String.valueOf(verificationCode[1])) &&
                thirdDigitTF.getText().equals(String.valueOf(verificationCode[2])) &&
                fourthDigitTF.getText().equals(String.valueOf(verificationCode[3]))) {
            mongoManager.createAccount(username, password, emailAddress);
            JOptionPane.showMessageDialog(rootPane, "Registration is successful!");
            firstDigitTF.setText("");
            secondDigitTF.setText("");
            thirdDigitTF.setText("");
            fourthDigitTF.setText("");
            guiManager.loadFrame("loginFrame");
        }
    }//GEN-LAST:event_confirmBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerificationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerificationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerificationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerificationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerificationGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmBTN;
    private javax.swing.JTextField firstDigitTF;
    private javax.swing.JTextField fourthDigitTF;
    private javax.swing.JLabel help1LBL;
    private javax.swing.JLabel help2LBL;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField secondDigitTF;
    private javax.swing.JTextField thirdDigitTF;
    private javax.swing.JLabel titleLBL;
    // End of variables declaration//GEN-END:variables
}
